# cutains information
measurement_errorpos: 0.1
measurement_errorvel: 0.0
delay: 0.0

# Names of joints in correct outputted order
joint_names: [
  "pelvis", "lHip", "rHip", "belly", "lKnee",
  "rKnee", "spine", "lAnkle", "rAnkle", "thor",
  "lToe", "rToe", "neck", "lClav", "rClav",
  "head", "lShldr", "rShldr", "lElbow",
  "rElbow", "lWrist", "rWrist", "lHand", "rHand",
  "nose", "eyes", "lEar", "rEar", "htop_mpi_inf_hp"
]
joint_v_max: [
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2,
  2, 2, 2, 2, 2
]

joint_a_max: [
  30, 30, 30, 30, 30,
  30, 30, 30, 30, 30,
  30, 30, 30, 30, 30,
  30, 30, 30, 30, 30,
  30, 30, 30, 30, 30,
  30, 30, 30, 30, 30
]
# All values are in the 95% Quantiles defined in DIN 33402-2
# There are no values about arm circumfence, so we take the leg values as overapproximation.
bodies:
  - name: "lUpperArm" 
    proximal: "lShldr"
    distal: "lElbow"
    thickness: 0.1 # 95 percentile of upper leg radius according to DIN 33402-2:2020-12 (There is no information on upper arm radius.)

  - name: "lLowerArm"
    proximal: "lElbow"
    distal: "lWrist"
    thickness: 0.066 # 95 percentile of lower leg radius according to DIN 33402-2:2020-12 (There is no information on lower arm radius.)

  - name: "lHand"
    proximal: "lWrist"
    distal: "lHand"
    thickness: 0.103 # 95 percentile of hand length according to DIN 33402-2:2020-12

  - name: "rUpperArm" 
    proximal: "rShldr"
    distal: "rElbow"
    thickness: 0.1 # 95 percentile of upper leg radius according to DIN 33402-2:2020-12 (There is no information on upper arm radius.)

  - name: "rLowerArm"
    proximal: "rElbow"
    distal: "rWrist"
    thickness: 0.066 # 95 percentile of lower leg radius according to DIN 33402-2:2020-12 (There is no information on lower arm radius.)

  - name: "rHand"
    proximal: "rWrist"
    distal: "rHand"
    thickness: 0.103 # 95 percentile of hand length according to DIN 33402-2:2020-12

  - name: "Torso"
    proximal: "pelvis"
    distal: "neck"
    thickness: 0.217 # Lays in 95% of shoulder width according to DIN 33402-2:2020-12
  
  - name: "Head"
    proximal: "neck"
    distal: "head"
    thickness: 0.217 # Lays in 95% of shoulder width according to DIN 33402-2:2020-12

extremities:
  - name: "lArm"
    base: "lShldr"
    end: "lHand"
    length: 0.825 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0
    
  - name: "rArm"
    base: "rShldr"
    end: "rHand"
    length: 0.825 # See Tabelle 21 — Reichweite nach vorn (Griffachse) - Half a hand length.
    thickness: 0.0